DROP TABLE IF EXISTS QUIZ;

CREATE TABLE QUIZ (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS QUESTIONS;

CREATE TABLE QUESTIONS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    options VARCHAR(250) NOT NULL,
    correct_option INT NOT NULL,
    quiz_id INT NOT NULL,
    points INT NOT NULL,
    FOREIGN KEY (quiz_id) REFERENCES QUIZ(id)
);